name: Agente Medicamentos

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  verificar-estoque:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar os arquivos do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: pip install openpyxl

      - name: Executar o agente
        env:
          MEU_NUMERO:        ${{ secrets.MEU_NUMERO }}
          CALLMEBOT_APIKEY:  ${{ secrets.CALLMEBOT_APIKEY }}
          MEU_NUMERO2:       ${{ secrets.MEU_NUMERO2 }}
          CALLMEBOT_APIKEY2: ${{ secrets.CALLMEBOT_APIKEY2 }}
        run: python agente_medicamentos.py
