name: Agente Medicamentos

on:
  schedule:
    - cron: '30 19 * * *'
  workflow_dispatch:

jobs:
  verificar-estoque:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar os arquivos do repositorio
        uses: actions/checkout@v4.2.2

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas
        run: pip install openpyxl twilio python-dotenv

      - name: Executar o agente
        env:
          TWILIO_ACCOUNT_SID:   ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN:    ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          MEUS_NUMEROS:         ${{ secrets.MEUS_NUMEROS }}
        run: python agente_medicamentos.py
